name: notatnik
summary: Notatnik
version: 1.0
description: Notatnik-edytor tekstu
type: app
grade: stable
confinement: strict
plugs:
  kde-frameworks-5-plug:
    content: kde-frameworks-5-46-qt-5-11-ubuntu-1604
    default-provider: kde-frameworks-5
    interface: content
    target: kf5
parts:
    2.projekt-notatnik:
        plugin: make
        source: 2.projekt-notatnik.zip
apps:
  notatnik:
    command: 2.projekt-notatnik
    plugs: [home, desktop, x11, opengl, kde-frameworks-5-plug]
